name = "codebases-api"
main = "src/index.ts"
compatibility_date = "2024-04-27"

[dev]
port = 8080

[[d1_databases]]
binding = "DB"
database_name = "codebases-db"
database_id = "a0fc507d-8bbc-4221-8e72-58aba52ee622"
migrations_dir = "db/migrations"
