name = "codebases-api"
main = "src/index.ts"
compatibility_date = "2024-04-27"

[dev]
port = 8080

[[d1_databases]]
binding = "DB"
database_name = "codebases-db"
database_id = "286bb219-cade-4a9f-8119-c5fc92c8e8e6"
